name: Coverage

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync

      - name: Install precommit
        run: uv pip install pre-commit

      - name: Run precommit hooks
        run: uv run pre-commit run --all-files

      - name: Run pipeline tests with coverage
        run: uv run --group PyZXLayer --group dev --group QiskitBicycleLayer --group QiskitPBCLayer --group NWQECTranspilationLayer --group NWQECPauliLayer pytest --cov --cov-branch --cov-report=xml -m build

      - name: Run lattice surgery tests with coverage
        run: uv run --group PyZXLayer --group TopologiqLayer --group TQECLayer pytest --cov --cov-branch --cov-append -m lattice_surgery

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
